"""Add oauth_accounts table and make hashed_password nullable

Revision ID: 09cffeef4f6b
Revises: 65c5e00d2c2c
Create Date: 2025-11-14 12:58:31.709322

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '09cffeef4f6b'
down_revision = '65c5e00d2c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('oauth_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('account_email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oauth_name', 'account_id', name='uq_oauth_provider_account')
    )
    op.create_index(op.f('ix_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False)
    op.drop_index(op.f('idx_companies_tenant_id'), table_name='companies')
    op.create_index(op.f('ix_companies_tenant_id'), 'companies', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('companies_tenant_id_fkey'), 'companies', type_='foreignkey')
    op.create_foreign_key(None, 'companies', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('locations', 'address',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index(op.f('idx_locations_company_id'), table_name='locations')
    op.create_index(op.f('ix_locations_company_id'), 'locations', ['company_id'], unique=False)
    op.drop_constraint(op.f('locations_company_id_fkey'), 'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'companies', ['company_id'], ['id'])
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('idx_users_tenant_id'), table_name='user')
    op.create_index(op.f('ix_user_tenant_id'), 'user', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('user_tenant_id_fkey'), 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(op.f('user_tenant_id_fkey'), 'user', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_tenant_id'), table_name='user')
    op.create_index(op.f('idx_users_tenant_id'), 'user', ['tenant_id'], unique=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.create_foreign_key(op.f('locations_company_id_fkey'), 'locations', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_locations_company_id'), table_name='locations')
    op.create_index(op.f('idx_locations_company_id'), 'locations', ['company_id'], unique=False)
    op.alter_column('locations', 'address',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key(op.f('companies_tenant_id_fkey'), 'companies', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_companies_tenant_id'), table_name='companies')
    op.create_index(op.f('idx_companies_tenant_id'), 'companies', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_oauth_accounts_user_id'), table_name='oauth_accounts')
    op.drop_constraint('uq_oauth_provider_account', 'oauth_accounts', type_='unique')
    op.drop_table('oauth_accounts')
    # ### end Alembic commands ###
